### ISSUE TITLE
Bug: 部分情况下会加载失败

### ISSUE THREAD

**Issue by OREOCODEDEV** [he0119/nonebot-plugin-datastore#111]
### 描述问题

在NoneBot2启动的插件加载阶段，datastore插件在加载时有概率会引发一个由sqlalchemy抛出的ValueError，导致所有依赖datastore相关的插件都无法使用

### 如何复现

在NoneBot2启动阶段概率出现该问题，以下为琢磨出来的怪特征：
1.在所有插件中如果第一次require成功加载了，那后面的插件的require都会成功
2.在所有插件中如果第一次require失败了，那后面插件的require都会失败
3.尝试关闭fastapi_reload启动NoneBot2，依然会出现该问题
4.通过fastapi_reload或手动使用nb run重新加载NoneBot2，都有概率成功或失败
~~5.貌似最近失败概率变高了好多，以前都是低概率出现的所以懒得管它，但是最近好像加载两三次才有一次成功~~

### 环境信息

- OS: Windows7 SP1
- Python 版本: 3.8.10
- Nonebot 版本: 2.0.0rc2
- 插件版本: v0.5.10（通过git clone安装）（具体的版本不记得了www，但是刚刚更新到了0.5.10依然有这个问题）
- sqlalchemy版本: 1.4.41

### 截图或日志

![image](https://user-images.githubusercontent.com/44545625/225567598-fe391fd9-124d-4a53-8ee3-84ad77314bb3.png)
![image](https://user-images.githubusercontent.com/44545625/225567889-6649b729-2458-4f7c-98a1-96e68c08ead2.png)

**Comment by he0119** [comment]
你要不用代码块，粘贴日志。截图看起来太累了🤣

```log
比如这种
```
