### ISSUE TITLE
无法读取环境变量配置的问题

### ISSUE THREAD

**Issue by felinae98** [he0119/nonebot-plugin-datastore#15]
https://github.com/he0119/nonebot-plugin-datastore/blob/5857ae5bef614b4c1f360f58e3e13bf432e33776/nonebot_plugin_datastore/config.py#L17
这个地方应该继承BaseSettings
因为nonebot的global_config对环境变量和envfile的处理有差异，写在envfile里的文件会全部load进global_config，插件config从global_config中初始化会带上global_config load的envfile里的值
但是，global_config**不会**load自己不认识的环境变量，所以如果这里使用BaseModel的话，是没有办法将环境变量的值引入插件config的，需要使用BaseSetting来自己读取环境变量中的值

**Comment by he0119** [comment]
惊，原来还有这种坑。

**Comment by he0119** [comment]
我去问了一下，就是这样设计的。必须要先在 .env 文件中配置所需配置项，nonebot 才会在环境变量中读取。

> CUSTOM_CONFIG2=  # 留空则从系统环境变量读取，如不存在则为空字符串

文档里确实没有说清楚。
