### ISSUE TITLE
nb新版本方法更新导致插件导入失败

### ISSUE THREAD

**Issue by TheValkyrja** [he0119/nonebot-plugin-datastore#30]
NB 2.0.0-rc1版本移除了过时的Export功能，导致插件在bot启动时导入失败并引发后续插件依赖报错。
希望修复。

10-05 09:00:00 [ERROR] nonebot | Failed to import "nonebot_plugin_datastore"
Traceback (most recent call last):
 （略）
**ImportError: cannot import name 'export' from 'nonebot.plugin' (/usr/local/lib/python3.10/dist-packages/nonebot/plugin/__init__.py)**

> Remove: 删除过时的 Export 功能 [@yanyongyu](https://github.com/yanyongyu) ([#1125](https://github.com/nonebot/nonebot2/pull/1125))

**Comment by he0119** [comment]
嗯，我待会儿就发一个新版 `0.3.4` 限制 nonebot2 版本号，然后再发一个 `0.4.0` 删除这个。
