### ISSUE TITLE
[提议] 使用toml作为config存储格式

### ISSUE THREAD

**Issue by shoucandanghehe** [he0119/nonebot-plugin-datastore#74]
理由：

1. 人类友好，方便阅读，改善开发者体验
2. toml 已经在 Python 中大量使用，比如PEP 621 的 pyproject.toml，以及 PEP 680 在Python3.11 中添加了新内置库 tomllib

值得注意的地方：
toml 不支持 ”**空**“ 值 ( _None_ )

以及一个可选项将所有插件的配置项保存至一个文件（？

**Comment by he0119** [comment]
我记得现在配置只支持 k-v 吧，用什么存感觉区别都不大（

都放一起是为什么需要这样？方便备份吗？

**Comment by shoucandanghehe** [comment]
> 我记得现在配置只支持 k-v 吧，用什么存感觉区别都不大（突然发现我怎么没有限制 v 是字符串，寄，这下怎么搬上数据库…也许还能用 json 字段抢救一下。）

现在 v 的 type 是 Any，甚至给一个 class typecheck都没报错（
json dump 的时候会报错就是了（

> 都放一起是为什么需要这样呢？方便备份吗？

备份 分享 以及用终端手动编辑文件的时候不用切来切去（？
还有现在的 config 存储似乎没有对同时运行的多个 bot 做一些特殊处理，只能手动指定路径
如果单文件存所有插件只需要拿到 bot 项目的 name 然后存到 name.toml

**Comment by he0119** [comment]
> 备份 分享 以及用终端手动编辑文件的时候不用切来切去（？
emmmm，备份整个文件夹感觉也差不多吧…不过做这个功能也不麻烦就是了，还可以顺便把存到数据库一起写了，直接发1.0.0（

> 还有现在的 config 存储似乎没有对同时运行的多个 bot 做一些特殊处理，只能手动指定路径
> 如果单文件存所有插件只需要拿到 bot 项目的 name 然后存到 name.toml

多机器人还是建议自己设置每个机器人的存储路径。并不会比自动识别机器人项目名称麻烦多少。不过这个我思考过要不要加一个 in-project 的设置，直接保存在项目目录中。

**Comment by he0119** [comment]
发布了一个 0.6.0a1 版本，支持多种格式了。不过因为要支持数据库，将 get 和 set 修改为了异步。数据库也换成了 SQLAlchemy，有兴趣的话，可以试试（
