### ISSUE TITLE
数据库连接断开

### ISSUE THREAD

**Issue by zhangao4833** [he0119/nonebot-plugin-datastore#94]
使用远程数据库连接时，几十分钟不访问就会出现数据库连接断开错误，可以在引擎初始化的时候使用连接池进行加载吗：
(pymysql.err.operationalerror) (2013, 'lost connection to mysql server during query ([winerror 121] 信号灯超时时间已到

**Comment by he0119** [comment]
你用的是什么 driver 呢？我记得除了 sqlite 其他都是默认启用连接池的。也许你需要设置的是 pool_recycle。
不过确实需要加一个设置传递参数给 create_engine。

**Comment by he0119** [comment]
对了，推荐文档 <https://docs.sqlalchemy.org/en/20/core/pooling.html#dealing-with-disconnects>。

**Comment by he0119** [comment]
新版发布了，试试？

**Comment by zhangao4833** [comment]
嗯嗯，我改了源码，加了参数pool_recycle就可以了，目前pip里面还没有0.5.10版本

**Comment by he0119** [comment]
<https://pypi.org/project/nonebot-plugin-datastore/0.5.10/>

已经有了，可能是你镜像的问题。

**Comment by zhangao4833** [comment]
嗯嗯，pypi有了，阿里的还没同步过去
